apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "demo-identity-server.name" . }}-dp-claim
  labels:
    app: {{ template "demo-identity-server.name" . }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
