apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "demo-web-api.name" . }}-pv-claim
  labels:
    app: {{ template "demo-web-api.name" . }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
